console.log(typeof 23.5);   // 'number'      
console.log(typeof 'Call me Ishmael.'); // 'string' 
console.log(typeof false);    // 'boolean'
console.log(typeof 0);    // 'number'
console.log(typeof null); // 'object'
console.log(typeof undefined); // 'undefined'